New admin utility dirchmod; utility bug fixes and enhancements

diff --git a/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/geoip b/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/geoip
--- a/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/geoip
+++ b/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/geoip
@@ -42,21 +42,21 @@
 
 # Load /etc/devops/ansi.conf if ANSI_CONFIG is unset
 if [ -z "$ANSI_CONFIG" ] && [ -f /etc/devops/ansi.conf ]; then
-  source /etc/devops/ansi.conf
+	source /etc/devops/ansi.conf
 fi
 
 ${ANSI_CONFIG?"[1;38;2;255;100;100mCannot load '/etc/devops/ansi.conf': No such file[0m"}
 
 # Load /etc/devops/exec.conf if EXEC_CONFIG is unset
 if [ -z "$EXEC_CONFIG" ] && [ -f /etc/devops/exec.conf ]; then
-  source /etc/devops/exec.conf
+	source /etc/devops/exec.conf
 fi
 
 ${EXEC_CONFIG?"${bold}${bittersweet}Cannot load '/etc/devops/exec.conf': No such file${reset}"}
 
 # Load /etc/devops/functions.conf if FUNC_CONFIG is unset
 if [ -z "$FUNC_CONFIG" ] && [ -f /etc/devops/functions.conf ]; then
-  source /etc/devops/functions.conf
+	source /etc/devops/functions.conf
 fi
 
 ${FUNC_CONFIG?"${bold}${bittersweet}Cannot load '/etc/devops/functions.conf': No such file${reset}"}
@@ -64,27 +64,27 @@ ${FUNC_CONFIG?"${bold}${bittersweet}Cannot load '/etc/devops/functions.conf': No
 ################################## Functions ##################################
 
 # ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
-# Function:	showHelp
-# Description:	Displays the usage message to the user
+# Function:     showHelp
+# Description:  Displays the usage message to the user
 # -----------------------------------------------------------------------------
 function showHelp() {
-  # BEGIN showHelp function
+	# BEGIN showHelp function
 
-  printUsage "geoip COMMAND ${gold}[OPTION]... [IP_ADDR] [DATA PATH]"
+	printUsage "geoip COMMAND ${gold}[OPTION]... [IP_ADDR] [DATA PATH]"
 
-  echo ${bold}
-  echo "Valid Commands:${romantic}"
-  echo '  lookup	Performs look up of an IP address in a MaxMind DB file'
-  echo '  status	Display creation date of the GeoLite2 database file'
-  echo '  update	Downloads and updates the GeoLite2 database'
+	echo ${bold}
+	echo "Valid Commands:${romantic}"
+	echo '  lookup	Performs look up of an IP address in a MaxMind DB file'
+	echo '  status	Display creation date of the GeoLite2 database file'
+	echo '  update	Downloads and updates the GeoLite2 database'
 
-  echo ${white}
-  echo "Valid Options:${romantic}"
-  echo '  -d directory	Specify a custom directory containing the GeoLite2 database'
-  echo '  -f filename	Specify a custom path to a single GeoLite2 database file'
-  echo ${reset}
+	echo ${white}
+	echo "Valid Options:${romantic}"
+	echo '  -d directory	Specify a custom directory containing the GeoLite2 database'
+	echo '  -f filename	Specify a custom path to a single GeoLite2 database file'
+	echo ${reset}
 
-  # END showHelp function
+	# END showHelp function
 }
 
 ################################## Variables ##################################
@@ -111,182 +111,171 @@ clParams="$@"
 
 # Display usage if no parameters given
 if [ -z $command ]; then
-  showHelp
-
-  exit 1
+	showHelp
+	exit 1
 fi
 
 # Display error if invalid command
 if [ $(containsElement "$command" "${validCommands[@]}") != '0' ]; then
-  printError 'geoip' "Invalid command: $command"
-  echo
+	printError 'geoip' "Invalid command: $command"
+	echo
+	showHelp
 
-  showHelp
-
-  exit 1
+	exit 1
 fi
 
 # Display error if not running as root
-if [ $(containsElement "$command" "${sudoCommands[@]}") == '0' ] && [ "$EUID" -ne 0 ]; then
-  echo "${bold}geoip: ${bittersweet}Permission denied (you must be root)${reset}"
-
-  exit 1
+if [ $(containsElement "$command" "${sudoCommands[@]}") == '0' ] && [ "$USER" != 'root' ]; then
+	printError 'geoip' 'Permission denied (you must be root)'
+	exit 1
 fi
 
 # Process command-line options, if present
 while [[ "$1" =~ ^- ]]; do
 
-  if [ "$1" == '-d' ]; then
+	if [ "$1" == '-d' ]; then
+		# Display error if directory parameter is missing or invalid
+		errorMessage=$(isValidDirectory 'geoip' "$2")
 
-    errorMessage=$(isValidDirectory 'geoip' "$2")
+		if [ "$errorMessage" != '0' ]; then
+			echo "$errorMessage"
+			echo
 
-    # Display error if directory parameter is missing or invalid
-    if [ "$errorMessage" != '0' ]; then
-      echo "$errorMessage"
-      echo
+			if [ $command == 'lookup' ]; then
+				printUsage "geoip $command -d directory IP_ADDR ${gold}[DATA PATH]"
+			else
+				printUsage "geoip $command -d directory"
+			fi
 
-      if [ $command == 'lookup' ]; then
-	printUsage "geoip $command -d directory IP_ADDR ${gold}[DATA PATH]"
-      else
-	printUsage "geoip $command -d directory"
-      fi
+			exit 1
+		fi
 
-      exit 1
-    fi
+		# Use geolocation database directory provided by user
+		geoDbDir="$2"
+		shift 2
 
-    # Use geolocation database directory provided by user
-    geoDbDir="$2"
+	elif [ "$1" == '-f' ]; then
+		# Display error if file parameter is missing or invalid
+		errorMessage=$(isValidFile 'geoip' "$2")
 
-    shift 2
+		if [ "$errorMessage" != '0' ]; then
+			echo "$errorMessage"
+			echo
 
-elif [ "$1" == '-f' ]; then
+			if [ $command == 'lookup' ]; then
+				printUsage "geoip $command -f filename IP_ADDR ${gold}[DATA PATH]"
+			else
+				printUsage "geoip $command -f filename"
+			fi
 
-    errorMessage=$(isValidFile 'geoip' "$2")
+			exit 1
+		fi
 
-    # Display error if file parameter is missing or invalid
-    if [ "$errorMessage" != '0' ]; then
-      echo "$errorMessage"
-      echo
+		# Use geolocation database file provided by user
+		geoDbFile="$2"
+		shift 2
+	else
+		# Display usage and error if option parameter is not valid
+		printError 'geoip' "Invalid option: $1"
+		echo
+		showHelp
 
-      if [ $command == 'lookup' ]; then
-	printUsage "geoip $command -f filename IP_ADDR ${gold}[DATA PATH]"
-      else
-	printUsage "geoip $command -f filename"
-      fi
-
-      exit 1
-    fi
-
-    # Use geolocation database file provided by user
-    geoDbFile="$2"
-
-    shift 2
-
-  else
-    # Display usage and error if option parameter is not valid
-    printError 'geoip' "Invalid option: $1"
-    echo
-
-    showHelp
-
-    exit 1
-  fi
-
+		exit 1
+	fi
 done
 
-errorMessage=$(isValidFile 'geoip' "$geoDbDir/$geoDbFile")
+if [ $command != 'update' ]; then
+	# Display error if MMDB file is missing or invalid
+	errorMessage=$(isValidFile 'geoip' "$geoDbDir/$geoDbFile")
 
-# Display error if MMDB file is missing or invalid
-if [ "$errorMessage" != '0' ]; then
-  echo "$errorMessage"
-
-  exit 1
+	if [ "$errorMessage" != '0' ]; then
+		echo "$errorMessage"
+		exit 1
+	fi
 fi
 
 # Display usage if only option parameters given for lookup command
 if [ -z "$1" ] && [ $command == 'lookup' ]; then
-  if [ -z "$clParams" ]; then
-    printUsage "geoip lookup IP_ADDR ${gold}[DATA PATH]"
-  else
-    printUsage "geoip lookup $clParams IP_ADDR ${gold}[DATA PATH]"
-  fi
+	if [ -z "$clParams" ]; then
+		printUsage "geoip lookup IP_ADDR ${gold}[DATA PATH]"
+	else
+		printUsage "geoip lookup $clParams IP_ADDR ${gold}[DATA PATH]"
+	fi
 
-  exit 1
+	exit 1
 fi
 
 ################################### Actions ###################################
 
 if [ $command == 'lookup' ]; then
-  # BEGIN IP address lookup
+	# BEGIN IP address lookup
 
-  ## IP Address
-  ipAddr="$1"
-  shift
+	## IP Address
+	ipAddr="$1"
+	shift
 
-  # Display error if IP Address is invalid
-  if ! $EXEC_VERIFYIP "$ipAddr"; then
-    printError 'geoip' "Invalid IP Address: $ipAddr"
-    echo
+	# Display error if IP Address is invalid
+	if ! $EXEC_VERIFYIP "$ipAddr"; then
+		printError 'geoip' "Invalid IP Address: $ipAddr"
+		echo
 
-    if [ -z "$clParams" ]; then
-      printUsage "geoip lookup IP_ADDR ${gold}[DATA PATH]"
-    else
-      printUsage "geoip lookup $clParams IP_ADDR ${gold}[DATA PATH]"
-    fi
+		if [ -z "$clParams" ]; then
+			printUsage "geoip lookup IP_ADDR ${gold}[DATA PATH]"
+		else
+			printUsage "geoip lookup $clParams IP_ADDR ${gold}[DATA PATH]"
+		fi
 
-    exit 1
-  fi
+		exit 1
+	fi
 
-  ## Data Path
-  dataPath="${@}"
+	## Data Path
+	dataPath="${@}"
 
-  if [ ${#dataPath} -eq 0 ]; then
-    $GEOIPLOOKUP --file "$geoDbDir/$geoDbFile" --ip ${ipAddr}
-  else
-    $GEOIPLOOKUP --file "$geoDbDir/$geoDbFile" --ip ${ipAddr} ${dataPath}
-  fi
+	if [ ${#dataPath} -eq 0 ]; then
+		$GEOIPLOOKUP --file "$geoDbDir/$geoDbFile" --ip ${ipAddr}
+	else
+		$GEOIPLOOKUP --file "$geoDbDir/$geoDbFile" --ip ${ipAddr} ${dataPath}
+	fi
 
-  # END IP address lookup
+	# END IP address lookup
 elif [ $command == 'status' ]; then
-  # BEGIN status command
 
-  $EXEC_STAT --format=%y "$geoDbDir/$geoDbFile"
+	$EXEC_STAT --format=%y "$geoDbDir/$geoDbFile"
 
-  # END status command
 elif [ $command == 'update' ]; then
-  # BEGIN update command
+	# BEGIN update command
 
-  printBanner 'Updating GeoLite2 City geolocation database'
+	printBanner 'Updating GeoLite2 City geolocation database'
 
-  echo "${bold}GeoLite2 DB Directory: ${wisteria}$geoDbDir"
-  echo "${white}GeoLite2 DB File: ${wisteria}$geoDbFile${reset}"
-  echo
+	echo "${bold}GeoLite2 DB Directory: ${wisteria}$geoDbDir"
+	echo "${white}GeoLite2 DB File: ${wisteria}$geoDbFile${reset}"
+	echo
 
-  # Create GeoLite2 directory
-  $EXEC_MKDIR --mode=0755 "$geoDbDir"
+	# Create GeoLite2 directory
+	$EXEC_MKDIR --mode=0755 "$geoDbDir"
 
-  printInfo 'Download latest GeoLite2 City database'
+	printInfo 'Download latest GeoLite2 City database'
 
-  # Download GeoLite2 City geolocation database
-  $EXEC_WGET -P "$geoDbDir" http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
+	# Download GeoLite2 City geolocation database
+	$EXEC_WGET -P "$geoDbDir" http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
 
-  printInfo 'Install GeoLite2 City database'
+	printInfo 'Install GeoLite2 City database'
 
-  # Untar GeoLite2-City.tar.gz file
-  $EXEC_TAR zxf "$geoDbDir/GeoLite2-City.tar.gz" --no-same-owner --no-same-permissions -C "$geoDbDir"
+	# Untar GeoLite2-City.tar.gz file
+	$EXEC_TAR zxf "$geoDbDir/GeoLite2-City.tar.gz" --no-same-owner --no-same-permissions -C "$geoDbDir"
 
-  newDBDir=$($EXEC_FIND "$geoDbDir" -type d -name "GeoLite2-City_*")
-  $EXEC_CHMOD 0755 "$newDBDir"
-  $EXEC_CHMOD 644 "$newDBDir/$geoDbFile"
+	newDBDir=$($EXEC_FIND "$geoDbDir" -type d -name "GeoLite2-City_*")
+	$EXEC_CHMOD 0755 "$newDBDir"
+	$EXEC_CHMOD 644 "$newDBDir/$geoDbFile"
 
-  # Move GeoLite2-City.mmdb file
-  $EXEC_MV "$newDBDir/$geoDbFile" "$geoDbDir"
+	# Move GeoLite2-City.mmdb file
+	$EXEC_MV "$newDBDir/$geoDbFile" "$geoDbDir"
 
-  # Remove GeoLite2-City directory and tar.gz file
-  $EXEC_RM -rf "$newDBDir"
-  $EXEC_RM "$geoDbDir/GeoLite2-City.tar.gz"
+	# Remove GeoLite2-City directory and tar.gz file
+	$EXEC_RM -rf "$newDBDir"
+	$EXEC_RM "$geoDbDir/GeoLite2-City.tar.gz"
 
-  # END update command
+	# END update command
 fi
 
 exit 0
diff --git a/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/verify b/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/verify
--- a/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/verify
+++ b/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/verify
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# sig - DevOpsBroker utility for creating and verifying PGP signatures of files
+# verify - DevOpsBroker utility for creating and verifying file hashes and signatures
 #
 # Copyright (C) 2018 Edward Smith <edwardsmith@devopsbroker.org>
 #
@@ -36,21 +36,21 @@
 
 # Load /etc/devops/ansi.conf if ANSI_CONFIG is unset
 if [ -z "$ANSI_CONFIG" ] && [ -f /etc/devops/ansi.conf ]; then
-  source /etc/devops/ansi.conf
+	source /etc/devops/ansi.conf
 fi
 
 ${ANSI_CONFIG?"[1;38;2;255;100;100mCannot load '/etc/devops/ansi.conf': No such file[0m"}
 
 # Load /etc/devops/exec.conf if EXEC_CONFIG is unset
 if [ -z "$EXEC_CONFIG" ] && [ -f /etc/devops/exec.conf ]; then
-  source /etc/devops/exec.conf
+	source /etc/devops/exec.conf
 fi
 
 ${EXEC_CONFIG?"${bold}${bittersweet}Cannot load '/etc/devops/exec.conf': No such file${reset}"}
 
 # Load /etc/devops/functions.conf if FUNC_CONFIG is unset
 if [ -z "$FUNC_CONFIG" ] && [ -f /etc/devops/functions.conf ]; then
-  source /etc/devops/functions.conf
+	source /etc/devops/functions.conf
 fi
 
 ${FUNC_CONFIG?"${bold}${bittersweet}Cannot load '/etc/devops/functions.conf': No such file${reset}"}
@@ -58,130 +58,144 @@ ${FUNC_CONFIG?"${bold}${bittersweet}Cannot load '/etc/devops/functions.conf': No
 ################################## Functions ##################################
 
 # ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
-# Function:	showHelp
-# Description:	Displays help message to the user
+# Function:     showMissingFilename
+# Description:  Displays usage information when the filename is missing
 # -----------------------------------------------------------------------------
-function showHelp() {
-  # BEGIN showHelp function
+function showMissingFilename() {
+	# BEGIN showMissingFilename function
 
-  if [ -z "$command" ]; then
-    printUsage "sig sign ${gold}[-a] ${yellow}FILE"
-    printUsage 'false' 'sig verify PGP_SIG FILE'
+	if [ "$command" == 'sha256' ]; then
+		printUsage "verify sha256 FILE ${gold}[SHA256_HASH]"
+	elif [ "$command" == 'sign' ]; then
+		printUsage "verify sign ${gold}[OPTION] ${yellow}FILE"
+		echo ${bold}
+		echo "Valid Options:${romantic}"
+		echo -e '  -a\t'       'Create an ASCII-format detached signature file'
+		echo ${reset}
+	elif [ "$command" == 'pgp' ]; then
+		printUsage 'verify pgp FILE SIG_FILE'
+	fi
 
-    echo ${bold}
-    echo "Valid Commands:${romantic}"
-    echo '  sign  	Create a detached signature of the specified FILE'
-    echo '  verify	Verify the specified FILE was signed using the detached signature PGP_SIG'
-    echo ${reset}
-
-  elif [ $command == 'sign' ]; then
-    printUsage "sig sign ${gold}[-a] ${yellow}FILE"
-
-    echo ${bold}
-    echo "Valid Options:${romantic}"
-    echo '  -a	Create an ASCII-format detached signature file'
-    echo ${reset}
-
-  elif [ $command == 'verify' ]; then
-    if [ -z "$sigFile" ]; then
-      printUsage 'sig verify PGP_SIG FILE'
-    else
-      printUsage "sig verify $sigFile FILE"
-    fi
-
-    echo
-  fi
-
-  # END showHelp function
+	# END showMissingFilename function
 }
 
 ################################## Variables ##################################
 
-validCommands=("sign" "verify")
+## Bash exec variables
+EXEC_SHA256SUM=/usr/bin/sha256sum
 
-# Options
+## Options
 command="$1"
-fileName=''
-asciiFormat='false'
+
+## Variables
+validCommands=('pgp' 'sha256' 'sign')
 
 #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ OPTION Parsing ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 # Display usage if no parameters given
 if [ -z "$command" ]; then
-  showHelp
-
-  exit 1
+	printUsage 'verify { pgp | sha256 | sign }'
+	exit 1
 fi
 
 # Display error if invalid command
 if [ $(containsElement "$command" "${validCommands[@]}") != '0' ]; then
-  printError 'sig' "Invalid command: '$command'"
-  command=''
-  echo
+	printError 'verify' "Invalid command: $command"
+	echo
+	printUsage 'verify { pgp | sha256 | sign }'
 
-  showHelp
-
-  exit 1
+	exit 1
 fi
 
-if [ $command == 'sign' ]; then
+if [ "$command" == 'sha256' ]; then
+	# File is the second parameter
+	fileName="$2"
 
-  if [ "$2" == '-a' ]; then
-    asciiFormat=true
+	# SHA256 Hash is the third parameter
+	sha256Hash="$3"
 
-    # File is the third parameter
-    fileName="$3"
-  else
-    # File is the second parameter
-    fileName="$2"
-  fi
+elif [ "$command" == 'sign' ]; then
 
-elif [ $command == 'verify' ]; then
+	if [ "$2" == '-a' ]; then
+		asciiFormat='true'
 
-  # Signature file is the second parameter
-  sigFile="$2"
+		# File is the third parameter
+		fileName="$3"
+	else
+		asciiFormat='false'
 
-  # File is the third parameter
-  fileName="$3"
+		# File is the second parameter
+		fileName="$2"
+	fi
 
-  errorMessage=$(isValidFile 'sig' "$sigFile")
+elif [ "$command" == 'pgp' ]; then
+	# File is the second parameter
+	fileName="$2"
 
-  # Display error if signature file parameter is missing or invalid
-  if [ "$errorMessage" != '0' ]; then
-    echo "$errorMessage"
-    echo
-    showHelp
+	# Signature file is the third parameter
+	sigFile="$3"
 
-    exit 1
-  fi
+	errorMessage=$(isValidFile 'verify' "$sigFile")
 
+	# Display error if signature file parameter is missing or invalid
+	if [ "$errorMessage" != '0' ]; then
+		echo "$errorMessage"
+		echo
+		printUsage 'verify pgp FILE SIG_FILE'
+
+		exit 1
+	fi
 fi
 
-errorMessage=$(isValidFile 'sig' "$fileName")
+errorMessage=$(isValidFile 'verify' "$fileName")
 
 # Display error if file parameter is missing or invalid
 if [ "$errorMessage" != '0' ]; then
-  echo "$errorMessage"
-  echo
-  showHelp
+	echo "$errorMessage"
+	echo
+	showMissingFilename
 
-  exit 1
+	exit 1
 fi
 
 ################################### Actions ###################################
 
-if [ "$command" == 'sign' ]; then
+if [ "$command" == 'pgp' ]; then
 
-  if [ "$asciiFormat" == 'false' ]; then
-    $EXEC_GPG --detach-sig "$fileName"
-  else
-    $EXEC_GPG --detach-sig -a "$fileName"
-  fi
+	$EXEC_GPG --verify "$sigFile" "$fileName"
 
-elif [ "$command" == 'verify' ]; then
+elif [ "$command" == 'sha256' ]; then
 
-  $EXEC_GPG --verify "$sigFile" "$fileName"
+	if [ -z "$sha256Hash" ]; then
 
+		# Compute SHA256 Hash for the given filename
+		$EXEC_SHA256SUM "$fileName"
+
+	else
+		if [ -f "$sha256Hash" ]; then
+
+			if ! $EXEC_GREP -Fq "$fileName" "$sha256Hash"; then
+				printError 'verify' "Cannot verify SHA256 hash for '$fileName': No such entry in '$sha256Hash'"
+				echo
+				exit 1
+			fi
+
+			$EXEC_SHA256SUM --check "$sha256Hash"
+
+		else
+			echo "$sha256Hash"  "$fileName" > verify-sha256sum.txt
+			$EXEC_SHA256SUM --check verify-sha256sum.txt
+			$EXEC_RM verify-sha256sum.txt
+		fi
+	fi
+
+elif [ "$command" == 'sign' ]; then
+
+	if [ "$asciiFormat" == 'false' ]; then
+		$EXEC_GPG --detach-sig "$fileName"
+	else
+		$EXEC_GPG --detach-sig -a "$fileName"
+	fi
 fi
 
 exit 0
diff --git a/Ubuntu/16.04/Desktop/Configurator/usr/local/sbin/dirchmod b/Ubuntu/16.04/Desktop/Configurator/usr/local/sbin/dirchmod
--- a/Ubuntu/16.04/Desktop/Configurator/usr/local/sbin/dirchmod
+++ b/Ubuntu/16.04/Desktop/Configurator/usr/local/sbin/dirchmod
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# kernel-config - DevOpsBroker script to display the current Linux kernel configuration
+# dirchmod - DevOpsBroker utility for changing only directory mode bits
 #
 # Copyright (C) 2018 Edward Smith <edwardsmith@devopsbroker.org>
 #
@@ -19,7 +19,7 @@
 # this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 # -----------------------------------------------------------------------------
-# Developed on Ubuntu 16.04.5 LTS running kernel.osrelease = 4.15.0-30
+# Developed on Ubuntu 16.04.5 LTS running kernel.osrelease = 4.15.0-33
 #
 # -----------------------------------------------------------------------------
 #
@@ -47,24 +47,46 @@ fi
 
 ${FUNC_CONFIG?"${bold}${bittersweet}Cannot load '/etc/devops/functions.conf': No such file${reset}"}
 
+# Display error if not running as root
+if [ "$USER" != 'root' ]; then
+	printError 'dirchmod' 'Permission denied (you must be root)'
+	exit 1
+fi
+
 ################################## Variables ##################################
 
 ## Options
-configParam="$1"
+dirMode="$1"
+dirName="$2"
 
-## Variables
-configFile="/boot/config-$(/bin/uname -r)"
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ OPTION Parsing ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+
+if [ -z "$dirMode" ]; then
+	printUsage 'dirchmod MODE DIR'
+	exit 1
+fi
+
+if [[ ! "$dirMode" =~ ^(4|2|1|0)?[0-7]{3}$ ]]; then
+	printError 'dirchmod' "Invalid mode '$dirMode'"
+	echo
+	printUsage 'dirchmod MODE DIR'
+
+	exit 1
+fi
+
+errorMessage=$(isValidDirectory 'dirchmod' "$dirName")
+
+# Display error if directory parameter is missing or invalid
+if [ "$errorMessage" != '0' ]; then
+	echo "$errorMessage"
+	echo
+	printUsage "dirchmod $dirMode DIR"
+
+	exit 1
+fi
 
 ################################### Actions ###################################
 
-if [ -f "$configFile" ]; then
-	if [ -z "$configParam" ]; then
-		$EXEC_CAT "$configFile"
-	else
-		$EXEC_GREP "$configParam" "$configFile"
-	fi
-else
-  printError 'kernel-config' "Cannot find '$configFile' kernel configuration file"
-fi
+$EXEC_FIND $dirName/ -type d -execdir $EXEC_CHMOD $dirMode {} +
 
 exit 0
