Made plenty of changes, fixes and refactorings due to testing results

diff --git a/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/geoip b/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/geoip
--- a/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/geoip
+++ b/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/geoip
@@ -38,27 +38,67 @@
 # -----------------------------------------------------------------------------
 #
 
-
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Preprocessing ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
-# Load /etc/dob/ansi.conf if bittersweet function does not exist
-if [[ ! "$(declare -F 'bittersweet')" ]]; then
-  . /etc/dob/ansi.conf
+# Load /etc/devops/ansi.conf if ANSI_CONFIG is unset
+if [ -z "$ANSI_CONFIG" ] && [ -f /etc/devops/ansi.conf ]; then
+  source /etc/devops/ansi.conf
 fi
 
-# Load /etc/dob/functions.conf if printBanner function does not exist
-if [[ ! "$(declare -F 'printBanner')" ]]; then
-  . /etc/dob/functions.conf
+${ANSI_CONFIG?"[1;38;2;255;100;100mCannot load '/etc/devops/ansi.conf': No such file[0m"}
+
+# Load /etc/devops/exec.conf if EXEC_CONFIG is unset
+if [ -z "$EXEC_CONFIG" ] && [ -f /etc/devops/exec.conf ]; then
+  source /etc/devops/exec.conf
 fi
 
-sudoCommands=("update")
-validCommands=("lookup" "status" "update")
+${EXEC_CONFIG?"${bold}${bittersweet}Cannot load '/etc/devops/exec.conf': No such file${reset}"}
 
+# Load /etc/devops/functions.conf if FUNC_CONFIG is unset
+if [ -z "$FUNC_CONFIG" ] && [ -f /etc/devops/functions.conf ]; then
+  source /etc/devops/functions.conf
+fi
+
+${FUNC_CONFIG?"${bold}${bittersweet}Cannot load '/etc/devops/functions.conf': No such file${reset}"}
+
+################################## Functions ##################################
+
+# ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
+# Function:	showHelp
+# Description:	Displays the usage message to the user
+# -----------------------------------------------------------------------------
+function showHelp() {
+  # BEGIN showHelp function
+
+  printUsage "geoip COMMAND ${gold}[OPTION]... [IP_ADDR] [DATA PATH]"
+
+  echo ${bold}
+  echo "Valid Commands:${romantic}"
+  echo '  lookup	Performs look up of an IP address in a MaxMind DB file'
+  echo '  status	Display creation date of the GeoLite2 database file'
+  echo '  update	Downloads and updates the GeoLite2 database'
+
+  echo ${white}
+  echo "Valid Options:${romantic}"
+  echo '  -d directory	Specify a custom directory containing the GeoLite2 database'
+  echo '  -f filename	Specify a custom path to a single GeoLite2 database file'
+  echo ${reset}
+
+  # END showHelp function
+}
+
+################################## Variables ##################################
+
+## Bash exec variables
+EXEC_VERIFYIP=/usr/local/bin/verifyip
 GEOIPLOOKUP=/usr/bin/mmdblookup
 
+sudoCommands=("update")
+validCommands=(${sudoCommands[@]} 'lookup' 'status')
+
 ## Options
-GEO_DB_DIR="/usr/share/GeoLite2"
-GEO_DB_FILE="GeoLite2-City.mmdb"
+geoDbDir="/usr/share/GeoLite2"
+geoDbFile="GeoLite2-City.mmdb"
 
 # Command is the first parameter
 command="$1"
@@ -67,54 +107,28 @@ shift
 # Original command-line parameters
 clParams="$@"
 
-
-################################## Functions ##################################
-
-# ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
-# Function:	showUsage
-# Description:	Displays the usage message to the user
-# -----------------------------------------------------------------------------
-function showUsage() {
-  # BEGIN showUsage function
-
-  printUsage "geoip COMMAND [OPTION]... [IP_ADDR] [DATA PATH]"
-  echo
-  echo -e "$(bold)Valid Commands:$(reset)"
-  echo -e "$(bold padua)  lookup$(reset)	Performs look up of an IP address in a MaxMind DB file"
-  echo -e "$(bold padua)  status$(reset)	Display creation date of the GeoLite2 database file"
-  echo -e "$(bold padua)  update$(reset)	Downloads and updates the GeoLite2 database"
-
-  echo
-  echo -e "$(bold)Valid Options:$(reset)"
-  echo -e "$(bold padua)  -d directory$(reset)	Specify a custom directory containing the GeoLite2 database"
-  echo -e "$(bold padua)  -f filename$(reset)	Specify a custom path to a single GeoLite2 database file"
-
-  # END showUsage function
-}
-
-
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~ COMMAND/OPTION Parsing ~~~~~~~~~~~~~~~~~~~~~~~~~~
-
-# Display error if not running as root
-if [ $(containsElement "$command" "${sudoCommands[@]}") == "0" ] && [ "$EUID" -ne 0 ]; then
-  echo -e "$(bold)geoip: $(bittersweet)Permission denied (you must be root)$(reset)"
-
-  exit 1
-fi
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ OPTION Parsing ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 # Display usage if no parameters given
-if [ -z "$command" ]; then
-  showUsage
+if [ -z $command ]; then
+  showHelp
 
   exit 1
 fi
 
 # Display error if invalid command
-if [ $(containsElement "$command" "${validCommands[@]}") != "0" ]; then
-  printError "geoip" "Invalid command $command"
+if [ $(containsElement "$command" "${validCommands[@]}") != '0' ]; then
+  printError 'geoip' "Invalid command: $command"
   echo
 
-  showUsage
+  showHelp
+
+  exit 1
+fi
+
+# Display error if not running as root
+if [ $(containsElement "$command" "${sudoCommands[@]}") == '0' ] && [ "$EUID" -ne 0 ]; then
+  echo "${bold}geoip: ${bittersweet}Permission denied (you must be root)${reset}"
 
   exit 1
 fi
@@ -122,25 +136,17 @@ fi
 # Process command-line options, if present
 while [[ "$1" =~ ^- ]]; do
 
-  if [ "$1" = "-d" ]; then
+  if [ "$1" == '-d' ]; then
 
-    # Display usage if no directory parameter given
-    if [ -z "$2" ]; then
-      if [ "$command" == "lookup" ]; then
-	printUsage "geoip $command -d directory IP_ADDR [DATA PATH]"
-      else
-	printUsage "geoip $command -d directory"
-      fi
+    errorMessage=$(isValidDirectory 'geoip' "$2")
 
-      exit 1
-    fi
-
-    # Display error if directory is invalid
-    if [ ! -d "$2" ]; then
-      printError "geoip" "Invalid directory $2"
+    # Display error if directory parameter is missing or invalid
+    if [ "$errorMessage" != '0' ]; then
+      echo "$errorMessage"
       echo
-      if [ "$command" == "lookup" ]; then
-	printUsage "geoip $command -d directory IP_ADDR [DATA PATH]"
+
+      if [ $command == 'lookup' ]; then
+	printUsage "geoip $command -d directory IP_ADDR ${gold}[DATA PATH]"
       else
 	printUsage "geoip $command -d directory"
       fi
@@ -149,29 +155,21 @@ while [[ "$1" =~ ^- ]]; do
     fi
 
     # Use geolocation database directory provided by user
-    GEO_DB_DIR="$2"
+    geoDbDir="$2"
 
     shift 2
 
-  elif [ "$1" = "-f" ]; then
+elif [ "$1" == '-f' ]; then
 
-    # Display usage if no file parameter given
-    if [ -z "$2" ]; then
-      if [ "$command" == "lookup" ]; then
-	printUsage "geoip $command -f filename IP_ADDR [DATA PATH]"
-      else
-	printUsage "geoip $command -f filename"
-      fi
+    errorMessage=$(isValidFile 'geoip' "$2")
 
-      exit 1
-    fi
-
-    # Display error if file is invalid
-    if [ ! -f "$2" ]; then
-      printError "geoiplookup" "Invalid filename $2"
+    # Display error if file parameter is missing or invalid
+    if [ "$errorMessage" != '0' ]; then
+      echo "$errorMessage"
       echo
-      if [ "$command" == "lookup" ]; then
-	printUsage "geoip $command -f filename IP_ADDR [DATA PATH]"
+
+      if [ $command == 'lookup' ]; then
+	printUsage "geoip $command -f filename IP_ADDR ${gold}[DATA PATH]"
       else
 	printUsage "geoip $command -f filename"
       fi
@@ -180,37 +178,45 @@ while [[ "$1" =~ ^- ]]; do
     fi
 
     # Use geolocation database file provided by user
-    GEO_DB_FILE="$2"
+    geoDbFile="$2"
 
     shift 2
 
   else
     # Display usage and error if option parameter is not valid
-    printError "geoip" "Invalid option $1"
+    printError 'geoip' "Invalid option: $1"
     echo
 
-    showUsage
+    showHelp
 
     exit 1
   fi
 
 done
 
+errorMessage=$(isValidFile 'geoip' "$geoDbDir/$geoDbFile")
+
+# Display error if MMDB file is missing or invalid
+if [ "$errorMessage" != '0' ]; then
+  echo "$errorMessage"
+
+  exit 1
+fi
+
 # Display usage if only option parameters given for lookup command
-if [ -z "$1" ] && [ "$command" == "lookup" ]; then
+if [ -z "$1" ] && [ $command == 'lookup' ]; then
   if [ -z "$clParams" ]; then
-    printUsage "geoip $command IP_ADDR [DATA PATH]"
+    printUsage "geoip lookup IP_ADDR ${gold}[DATA PATH]"
   else
-    printUsage "geoip $command $clParams IP_ADDR [DATA PATH]"
+    printUsage "geoip lookup $clParams IP_ADDR ${gold}[DATA PATH]"
   fi
 
   exit 1
 fi
 
-
 ################################### Actions ###################################
 
-if [ "$command" == "lookup" ]; then
+if [ $command == 'lookup' ]; then
   # BEGIN IP address lookup
 
   ## IP Address
@@ -218,10 +224,15 @@ if [ "$command" == "lookup" ]; then
   shift
 
   # Display error if IP Address is invalid
-  if ! verifyip "$ipAddr"; then
-    printError "geoip" "Invalid IP Address $ipAddr"
+  if ! $EXEC_VERIFYIP "$ipAddr"; then
+    printError 'geoip' "Invalid IP Address: $ipAddr"
     echo
-    printUsage "geoip $command [OPTION]... IP_ADDR [DATA PATH]"
+
+    if [ -z "$clParams" ]; then
+      printUsage "geoip lookup IP_ADDR ${gold}[DATA PATH]"
+    else
+      printUsage "geoip lookup $clParams IP_ADDR ${gold}[DATA PATH]"
+    fi
 
     exit 1
   fi
@@ -230,53 +241,52 @@ if [ "$command" == "lookup" ]; then
   dataPath="${@}"
 
   if [ ${#dataPath} -eq 0 ]; then
-    $GEOIPLOOKUP --file "$GEO_DB_DIR/$GEO_DB_FILE" --ip $ipAddr
+    $GEOIPLOOKUP --file "$geoDbDir/$geoDbFile" --ip ${ipAddr}
   else
-    $GEOIPLOOKUP --file "$GEO_DB_DIR/$GEO_DB_FILE" --ip $ipAddr $dataPath
+    $GEOIPLOOKUP --file "$geoDbDir/$geoDbFile" --ip ${ipAddr} ${dataPath}
   fi
 
   # END IP address lookup
-elif [ "$command" == "status" ]; then
+elif [ $command == 'status' ]; then
   # BEGIN status command
 
-  stat --format=%y "$GEO_DB_DIR/$GEO_DB_FILE"
+  $EXEC_STAT --format=%y "$geoDbDir/$geoDbFile"
 
   # END status command
-elif [ "$command" == "update" ]; then
+elif [ $command == 'update' ]; then
   # BEGIN update command
 
-  printBanner "Updating GeoLite2 City geolocation database"
+  printBanner 'Updating GeoLite2 City geolocation database'
 
-  echo -e "$(bold)GeoLite2 DB Directory:$(padua) $GEO_DB_DIR$(reset)"
-  echo -e "$(bold)GeoLite2 DB File:$(padua) $GEO_DB_FILE$(reset)"
+  echo "${bold}GeoLite2 DB Directory: ${wisteria}$geoDbDir"
+  echo "${white}GeoLite2 DB File: ${wisteria}$geoDbFile${reset}"
   echo
 
   # Create GeoLite2 directory
-  mkdir -p --mode=0755 "$GEO_DB_DIR"
+  $EXEC_MKDIR --mode=0755 "$geoDbDir"
 
-  printInfo "Download latest GeoLite2 City database"
+  printInfo 'Download latest GeoLite2 City database'
 
   # Download GeoLite2 City geolocation database
-  wget -P "$GEO_DB_DIR" http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
+  $EXEC_WGET -P "$geoDbDir" http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
 
-  printInfo "Install GeoLite2 City database"
+  printInfo 'Install GeoLite2 City database'
 
   # Untar GeoLite2-City.tar.gz file
-  tar zxf "$GEO_DB_DIR/GeoLite2-City.tar.gz" --no-same-owner --no-same-permissions -C "$GEO_DB_DIR"
+  $EXEC_TAR zxf "$geoDbDir/GeoLite2-City.tar.gz" --no-same-owner --no-same-permissions -C "$geoDbDir"
 
-  newDBDir=$(find "$GEO_DB_DIR" -type d -name "GeoLite2-City_*")
-  chmod 0755 "$newDBDir"
-  chmod 644 "$newDBDir/$GEO_DB_FILE"
+  newDBDir=$($EXEC_FIND "$geoDbDir" -type d -name "GeoLite2-City_*")
+  $EXEC_CHMOD 0755 "$newDBDir"
+  $EXEC_CHMOD 644 "$newDBDir/$geoDbFile"
 
   # Move GeoLite2-City.mmdb file
-  mv "$newDBDir/$GEO_DB_FILE" "$GEO_DB_DIR"
+  $EXEC_MV "$newDBDir/$geoDbFile" "$geoDbDir"
 
   # Remove GeoLite2-City directory and tar.gz file
-  rm -rf "$newDBDir"
-  rm "$GEO_DB_DIR/GeoLite2-City.tar.gz"
+  $EXEC_RM -rf "$newDBDir"
+  $EXEC_RM "$geoDbDir/GeoLite2-City.tar.gz"
 
   # END update command
 fi
 
 exit 0
-
diff --git a/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/sig b/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/sig
--- a/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/sig
+++ b/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/sig
@@ -3,7 +3,7 @@
 #
 # sig - DevOpsBroker utility for creating and verifying PGP signatures of files
 #
-# Copyright (C) 2018 AUTHOR_NAME <email@address.com>
+# Copyright (C) 2018 Edward Smith <edwardsmith@devopsbroker.org>
 #
 # This program is free software: you can redistribute it and/or modify it under
 # the terms of the GNU General Public License as published by the Free Software
@@ -32,81 +32,91 @@
 # -----------------------------------------------------------------------------
 #
 
-
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Preprocessing ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
-# Load /etc/dob/ansi.conf if bittersweet function does not exist
-if [[ ! "$(declare -F 'bittersweet')" ]]; then
-  . /etc/dob/ansi.conf
+# Load /etc/devops/ansi.conf if ANSI_CONFIG is unset
+if [ -z "$ANSI_CONFIG" ] && [ -f /etc/devops/ansi.conf ]; then
+  source /etc/devops/ansi.conf
 fi
 
-# Load /etc/dob/functions.conf if printBanner function does not exist
-if [[ ! "$(declare -F 'printBanner')" ]]; then
-  . /etc/dob/functions.conf
+${ANSI_CONFIG?"[1;38;2;255;100;100mCannot load '/etc/devops/ansi.conf': No such file[0m"}
+
+# Load /etc/devops/exec.conf if EXEC_CONFIG is unset
+if [ -z "$EXEC_CONFIG" ] && [ -f /etc/devops/exec.conf ]; then
+  source /etc/devops/exec.conf
 fi
 
+${EXEC_CONFIG?"${bold}${bittersweet}Cannot load '/etc/devops/exec.conf': No such file${reset}"}
+
+# Load /etc/devops/functions.conf if FUNC_CONFIG is unset
+if [ -z "$FUNC_CONFIG" ] && [ -f /etc/devops/functions.conf ]; then
+  source /etc/devops/functions.conf
+fi
+
+${FUNC_CONFIG?"${bold}${bittersweet}Cannot load '/etc/devops/functions.conf': No such file${reset}"}
 
 ################################## Functions ##################################
 
 # ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
 # Function:	showHelp
 # Description:	Displays help message to the user
-#
-# Parameter $1: The command passed to sig on the command-line (optional)
-# Parameter $2: The name of the signature file (optional)
 # -----------------------------------------------------------------------------
 function showHelp() {
   # BEGIN showHelp function
 
-  if [ -z "$1" ]; then
-    printUsage "sig sign [-a] FILE"
-    printUsage "false" "sig verify PGP_SIG FILE"
+  if [ -z "$command" ]; then
+    printUsage "sig sign ${gold}[-a] ${yellow}FILE"
+    printUsage 'false' 'sig verify PGP_SIG FILE'
 
-    echo
-    echo -e "$(bold)Valid Options:$(reset)"
-    echo -e "$(bold padua)  -a\t"		"Create an ASCII-format detached signature file"
-  elif [ "$1" == "sign" ]; then
-    printUsage "sig sign [-a] FILE"
+    echo ${bold}
+    echo "Valid Commands:${romantic}"
+    echo '  sign  	Create a detached signature of the specified FILE'
+    echo '  verify	Verify the specified FILE was signed using the detached signature PGP_SIG'
+    echo ${reset}
 
-    echo
-    echo -e "$(bold)Valid Options:$(reset)"
-    echo -e "$(bold padua)  -a\t"		"Create an ASCII-format detached signature file"
-  else
-    if [ -z "$2" ]; then
-      sigFile="SIG_FILE"
+  elif [ $command == 'sign' ]; then
+    printUsage "sig sign ${gold}[-a] ${yellow}FILE"
+
+    echo ${bold}
+    echo "Valid Options:${romantic}"
+    echo '  -a	Create an ASCII-format detached signature file'
+    echo ${reset}
+
+  elif [ $command == 'verify' ]; then
+    if [ -z "$sigFile" ]; then
+      printUsage 'sig verify PGP_SIG FILE'
     else
-      sigFile="$2"
+      printUsage "sig verify $sigFile FILE"
     fi
 
-    printUsage "sig verify $sigFile FILE"
+    echo
   fi
 
   # END showHelp function
 }
 
-
 ################################## Variables ##################################
 
 validCommands=("sign" "verify")
 
-GPG=/usr/bin/gpg
-
 # Options
 command="$1"
-asciiFormat=false
+fileName=''
+asciiFormat='false'
 
 #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ OPTION Parsing ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 # Display usage if no parameters given
-if [ -z "$1" ]; then
+if [ -z "$command" ]; then
   showHelp
 
   exit 1
 fi
 
 # Display error if invalid command
-if [ $(containsElement "$command" "${validCommands[@]}") != "0" ]; then
-  printError "sig" "Invalid command: $command"
+if [ $(containsElement "$command" "${validCommands[@]}") != '0' ]; then
+  printError 'sig' "Invalid command: '$command'"
+  command=''
   echo
 
   showHelp
@@ -114,81 +124,64 @@ if [ $(containsElement "$command" "${validCommands[@]}") != "0" ]; then
   exit 1
 fi
 
-# Display error if no file specified
-if [ -z "$2" ]; then
-  printError "sig" "Missing file parameter"
-  echo
+if [ $command == 'sign' ]; then
 
-  showHelp "$command"
+  if [ "$2" == '-a' ]; then
+    asciiFormat=true
+
+    # File is the third parameter
+    fileName="$3"
+  else
+    # File is the second parameter
+    fileName="$2"
+  fi
+
+elif [ $command == 'verify' ]; then
+
+  # Signature file is the second parameter
+  sigFile="$2"
+
+  # File is the third parameter
+  fileName="$3"
+
+  errorMessage=$(isValidFile 'sig' "$sigFile")
+
+  # Display error if signature file parameter is missing or invalid
+  if [ "$errorMessage" != '0' ]; then
+    echo "$errorMessage"
+    echo
+    showHelp
+
+    exit 1
+  fi
+
+fi
+
+errorMessage=$(isValidFile 'sig' "$fileName")
+
+# Display error if file parameter is missing or invalid
+if [ "$errorMessage" != '0' ]; then
+  echo "$errorMessage"
+  echo
+  showHelp
 
   exit 1
 fi
-
-if [ "$command" == "sign" ] && [ "$2" == "-a" ]; then
-  asciiFormat=true
-
-  shift
-
-  # Display error if no file specified
-  if [ -z "$2" ]; then
-    printError "sig" "Missing file parameter"
-    echo
-
-    showHelp "$command"
-
-    exit 1
-  fi
-fi
-
-# Display error if invalid file
-if [ ! -f "$2" ]; then
-  printError "sig" "Cannot access '$2': No such file"
-  echo
-
-  showHelp "$command"
-
-  exit 1
-fi
-
-if [ "$command" == "verify" ]; then
-
-  # Display error if no file specified
-  if [ -z "$3" ]; then
-    printError "sig" "Missing file parameter"
-    echo
-
-    showHelp "$command" "$2"
-
-    exit 1
-  fi
-
-  # Display error if invalid file
-  if [ ! -f "$3" ]; then
-    printError "sig" "Cannot access '$3': No such file"
-    echo
-
-    showHelp "$command"
-
-    exit 1
-  fi
-fi
-
 
 ################################### Actions ###################################
 
-if [ "$command" == "sign" ]; then
+if [ "$command" == 'sign' ]; then
 
-  if [ "$asciiFormat" == "false" ]; then
-    $GPG --detach-sig "$2"
+  if [ "$asciiFormat" == 'false' ]; then
+    $EXEC_GPG --detach-sig "$fileName"
   else
-    $GPG --detach-sig -a "$2"
+    $EXEC_GPG --detach-sig -a "$fileName"
   fi
 
-elif [ "$command" == "verify" ]; then
+elif [ "$command" == 'verify' ]; then
 
-  $GPG --verify "$2" "$3"
+  $EXEC_GPG --verify "$sigFile" "$fileName"
 
 fi
 
 exit 0
-
diff --git a/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/ssh-key b/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/ssh-key
--- a/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/ssh-key
+++ b/Ubuntu/16.04/Desktop/Configurator/usr/local/bin/ssh-key
@@ -40,19 +40,35 @@
 # -----------------------------------------------------------------------------
 #
 
-
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Preprocessing ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
-# Load /etc/dob/ansi.conf if bittersweet function does not exist
-if [[ ! "$(declare -F 'bittersweet')" ]]; then
-  . /etc/dob/ansi.conf
+# Load /etc/devops/ansi.conf if ANSI_CONFIG is unset
+if [ -z "$ANSI_CONFIG" ] && [ -f /etc/devops/ansi.conf ]; then
+  source /etc/devops/ansi.conf
 fi
 
-# Load /etc/dob/functions.conf if printBanner function does not exist
-if [[ ! "$(declare -F 'printBanner')" ]]; then
-  . /etc/dob/functions.conf
+${ANSI_CONFIG?"[1;38;2;255;100;100mCannot load '/etc/devops/ansi.conf': No such file[0m"}
+
+# Load /etc/devops/exec.conf if EXEC_CONFIG is unset
+if [ -z "$EXEC_CONFIG" ] && [ -f /etc/devops/exec.conf ]; then
+  source /etc/devops/exec.conf
 fi
 
+${EXEC_CONFIG?"${bold}${bittersweet}Cannot load '/etc/devops/exec.conf': No such file${reset}"}
+
+# Load /etc/devops/functions.conf if FUNC_CONFIG is unset
+if [ -z "$FUNC_CONFIG" ] && [ -f /etc/devops/functions.conf ]; then
+  source /etc/devops/functions.conf
+fi
+
+${FUNC_CONFIG?"${bold}${bittersweet}Cannot load '/etc/devops/functions.conf': No such file${reset}"}
+
+# Display error if running as root
+if [ "$EUID" -eq 0 ]; then
+  echo "${bold}ssh-key: ${bittersweet}Permission denied (you cannot be root)${reset}"
+
+  exit 1
+fi
 
 ################################## Functions ##################################
 
@@ -63,13 +79,12 @@ fi
 function findPrivateKey() {
   # BEGIN findPrivateKey function
 
-  privateKeyList=()
-  while IFS=  read -r -d $'\0'; do
-    privateKeyList+=("$REPLY")
-  done < <(find "$sshDir" -type f ! -name '*.pub' -print0)
+  echo "SSH directory: $sshDir"
+
+  privateKeyList=($($EXEC_GREP -Fl -d skip 'BEGIN OPENSSH PRIVATE KEY' "$sshDir"/*))
 
   if [ ${#privateKeyList[@]} -gt 1 ]; then
-    echo -e "$(bold)Which private SSH key do you want to work with?$(reset)"
+    echo ${bold}'Which private SSH key do you want to work with?'${reset}
     select privateKey in "${privateKeyList[@]}"; do
       break;
     done
@@ -91,10 +106,10 @@ function findPublicKey() {
   publicKeyList=()
   while IFS=  read -r -d $'\0'; do
     publicKeyList+=("$REPLY")
-  done < <(find "$sshDir" -type f -name '*.pub' -print0)
+  done < <($EXEC_FIND "$sshDir" -type f -name '*.pub' -print0)
 
   if [ ${#publicKeyList[@]} -gt 1 ]; then
-    echo -e "$(bold)Which public SSH key do you want to work with?$(reset)"
+    echo ${bold}'Which public SSH key do you want to work with?'${reset}
     select publicKey in "${publicKeyList[@]}"; do
       break;
     done
@@ -113,23 +128,23 @@ function findPublicKey() {
 function showHelp() {
   # BEGIN showHelp function
 
-  printUsage "ssh-key COMMAND [OPTION]..."
+  printUsage "ssh-key COMMAND ${gold}[OPTION]..."
 
-  echo
-  echo -e "$(bold)Valid Commands:$(reset)"
-  echo -e "$(bold padua)  clip$(reset)\t\t\t\t"				"Clips an SSH public key to the X11 clipboard"
-  echo -e "$(bold padua)  copy$(reset)\t\t\t\t"				"Copies an SSH public key to username@remote_server"
-  echo -e "$(bold padua)  fingerprint$(reset)\t\t\t"			"Shows fingerprint of all SSH public keys"
-  echo -e "$(bold padua)  generate$(reset)\t\t\t"			"Generates an SSH key pair in the $HOME/.ssh directory"
-  echo -e "$(bold padua)  list$(reset)\t\t\t\t"				"List all SSH public keys in the $HOME/.ssh directory"
-  echo -e "$(bold padua)  passphrase$(reset)\t\t\t"			"Change the passphrase of an existing SSH private key"
-  echo
-  echo -e "$(bold)Valid Options:$(reset)"
-  echo -e "$(bold padua)  -d $(yellow)DIRECTORY$(reset)\t\t\t"		"The directory where to find the .ssh/ subdirectory"
-  echo -e "$(bold padua)  -p $(yellow)PORT$(reset)\t\t\t"		"The port to use when copying an SSH public key to a remote server"
-  echo -e "$(bold padua)  -t $(yellow)ecdsa|ed25519|rsa|rsa1$(reset)\t"	"The key type to create; default is \"ed25519\""
-  echo -e "$(bold padua)  -u $(yellow)USERNAME$(reset)\t\t\t"		"The username who owns the SSH keys"
-  echo
+  echo ${bold}
+  echo "Valid Commands:${romantic}"
+  echo '  clip		Clips an SSH public key to the X11 clipboard'
+  echo '  copy		Copies an SSH public key to username@remote_server'
+  echo '  fingerprint	Shows fingerprint of all SSH public keys'
+  echo '  generate	Generates an SSH key pair in the $HOME/.ssh directory'
+  echo '  list		List all SSH public keys in the $HOME/.ssh directory'
+  echo '  passphrase	Change the passphrase of an existing SSH private key'
+  echo ${white}
+  echo "Valid Options:${romantic}"
+  echo '  -d DIRECTORY	The directory where to find the .ssh/ subdirectory'
+  echo '  -p PORT	The port to use when copying an SSH public key to a remote server'
+  echo '  -t KEYTYPE	The key type to create (ecdsa|ed25519|rsa|rsa1); default is "ed25519"'
+  echo '  -u USERNAME	The username who owns the SSH keys'
+  echo ${reset}
 
   # END showHelp function
 }
@@ -137,25 +152,33 @@ function showHelp() {
 
 ################################## Variables ##################################
 
-validCommands=("clip" "copy" "fingerprint" "gen" "generate" "list" "pass" "passphrase")
-
+## Bash exec variables
+EXEC_HOSTNAME=/bin/hostname
 SSH_COPY_ID=/usr/bin/ssh-copy-id
 SSH_KEYGEN=/usr/bin/ssh-keygen
 XCLIP=/usr/bin/xclip
 
+validCommands=("clip" "copy" "fingerprint" "gen" "generate" "list" "pass" "passphrase")
+
+## Options
+command="$1"
+keyType='ed25519'
+sshDir="$HOME/.ssh"
+sshPort='22'
+username=$USER
 
 #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ OPTION Parsing ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 # Display usage if incorrect parameters given
-if [ -z "$1" ]; then
+if [ -z "$command" ]; then
   showHelp
 
   exit 1
 fi
 
 # Ensure the first parameter is a valid command
-if [ $(containsElement "$1" "${validCommands[@]}") != "0" ]; then
-  printError "ssh-key" "Invalid command $1"
+if [ $(containsElement "$command" "${validCommands[@]}") != '0' ]; then
+  printError 'ssh-key' "Invalid command: $command"
   echo
 
   showHelp
@@ -164,65 +187,52 @@ if [ $(containsElement "$1" "${validCommands[@]}") != "0" ]; then
 fi
 
 ## Options
-command="$1"
-keyType="ed25519"
-sshDir="$HOME/.ssh"
-sshPort="22"
-username="$(whoami)"
 
 # Process command-line options, if present
 while [[ "$2" =~ ^- ]]; do
 
-  if [ "$2" == "-d" ]; then
+  if [ "$2" == '-d' ]; then
 
-    # Display error and usage if incorrect parameters given
-    if [ -z "$3" ]; then
-      printError "ssh-key" "Missing directory parameter"
-      echo
-      printUsage "ssh-key $command -d DIRECTORY"
+    errorMessage=$(isValidDirectory 'ssh-key' "$3")
 
-      exit 1
-    elif [ ! -d "$3" ]; then
-      printError "ssh-key" "Invalid directory: $3"
+    # Display error if directory parameter is missing or invalid
+    if [ "$errorMessage" != '0' ]; then
+      echo "$errorMessage"
       echo
-      printUsage "ssh-key $command -d DIRECTORY"
+      printUsage "ssh-key $command ${gold}-d DIRECTORY"
 
       exit 1
     fi
 
     sshDir="$3/.ssh"
 
-    if [ ! -d "$sshDir" ]; then
-      # Make SSH directory
-      mkdir -p --mode=0700 "$sshDir"
-
-      # Make directory to enable SSH multiplexing
-      mkdir -p --mode=0700 "$sshDir/multiplex"
-    fi
-
     shift 2
 
-  elif [ "$2" == "-p" ]; then
+  elif [ "$2" == '-p' ]; then
 
     # Display error and usage if incorrect parameters given
-    if [ "$command" != "copy" ]; then
-      printError "ssh-key" "Invalid command $command: Port number parameter"
+    if [ $command != 'copy' ]; then
+      printError 'ssh-key' 'Invalid parameter: -p'
       echo
-      printUsage "ssh-key copy -p PORT username@remote_server"
+      printUsage "ssh-key copy ${gold}-p PORT ${yellow}username@remote_server"
 
       exit 1
-    elif [ -z "$3" ]; then
-      printError "ssh-key" "Missing port number parameter"
+    fi
+
+    # Display error if no port number parameter given
+    if [ -z "$3" ]; then
+      printError 'ssh-key' 'Missing port number parameter'
       echo
-      printUsage "ssh-key copy -p PORT username@remote_server"
+      printUsage "ssh-key copy ${gold}-p PORT ${yellow}username@remote_server"
 
       exit 1
-    elif [[ ! "$3" =~ ^[0-9]+$ ]] || \
-	[ "$3" -lt 1 ] || \
-	[ "$3" -gt 65535]; then
-      printError "ssh-key" "Invalid port number: $3"
+    fi
+
+    # Display error if invalid port number parameter given
+    if [[ ! "$3" =~ ^[0-9]+$ ]] || [ "$3" -lt 1 ] || [ "$3" -gt 65535 ]; then
+      printError 'ssh-key' "Invalid port number: $3"
       echo
-      printUsage "ssh-key copy -p PORT username@remote_server"
+      printUsage "ssh-key copy ${gold}-p PORT ${yellow}username@remote_server"
 
       exit 1
     fi
@@ -230,19 +240,28 @@ while [[ "$2" =~ ^- ]]; do
     sshPort="$3"
     shift 2
 
-  elif [ "$2" == "-t" ]; then
+  elif [ "$2" == '-t' ]; then
 
     # Display error and usage if incorrect parameters given
-    if [ -z "$3" ]; then
-      printError "ssh-key" "Missing key type parameter"
+    if [ $command != 'gen' ] && [ $command != 'generate' ]; then
+      printError 'ssh-key' 'Invalid parameter: -t'
       echo
-      printUsage "ssh-key $command -t ecdsa|ed25519|rsa|rsa1"
+      printUsage "ssh-key generate ${gold}-t ecdsa|ed25519|rsa|rsa1"
+
+      exit 1
+    fi
+
+    # Display error if key type parameter is missing or invalid
+    if [ -z "$3" ]; then
+      printError 'ssh-key' 'Missing key type parameter'
+      echo
+      printUsage "ssh-key $command ${gold}-t ecdsa|ed25519|rsa|rsa1"
 
       exit 1
     elif [[ ! "$3" =~ ^(ecdsa|ed25519|rsa|rsa1)$ ]]; then
-      printError "ssh-key" "Invalid key type: $3"
+      printError 'ssh-key' "Invalid key type: $3"
       echo
-      printUsage "ssh-key $command -t ecdsa|ed25519|rsa|rsa1"
+      printUsage "ssh-key $command ${gold}-t ecdsa|ed25519|rsa|rsa1"
 
       exit 1
     fi
@@ -250,38 +269,46 @@ while [[ "$2" =~ ^- ]]; do
     keyType="$3"
     shift 2
 
-  elif [ "$2" == "-u" ]; then
+  elif [ "$2" == '-u' ]; then
 
     # Display error and usage if incorrect parameters given
-    if [ -z "$3" ]; then
-      printError "ssh-key" "Missing username parameter"
+    if [ $command != 'gen' ] && [ $command != 'generate' ]; then
+      printError 'ssh-key' 'Invalid parameter: -u'
       echo
-      printUsage "ssh-key $command -u USERNAME"
+      printUsage "ssh-key generate ${gold}-u USERNAME"
 
       exit 1
-    else
-      nsswitch="$(getent passwd $3)"
-
-      # Ensure the parameter is a valid username
-      if [ ${#nsswitch} -eq 0 ]; then
-	printError "ssh-key" "Invalid username: $3"
-	echo
-	printUsage "ssh-key $command -u USERNAME"
-
-	exit 1
-      fi
-
-      username="$3"
-      shift 2
-
     fi
+
+    errorMessage=$(isValidUsername 'ssh-key' "$3")
+
+    # Display error if username parameter is missing or invalid
+    if [ "$errorMessage" != '0' ]; then
+      echo "$errorMessage"
+      echo
+      printUsage "ssh-key $command ${gold}-u USERNAME"
+
+      exit 1
+    fi
+
+    username="$3"
+    shift 2
   fi
 done
 
-
 ################################### Actions ###################################
 
-if [ "$command" == "clip" ]; then
+# Make SSH directory (if necessary)
+if [ ! -d "$sshDir" ]; then
+  $EXEC_MKDIR --mode=0700 "$sshDir"
+fi
+
+# Make directory to enable SSH multiplexing (if necessary)
+if [ ! -d "$sshDir/multiplex" ]; then
+  $EXEC_MKDIR --mode=0700 "$sshDir/multiplex"
+fi
+
+if [ $command == 'clip' ]; then
   # BEGIN clip command
 
   # Find the public key the user wants to clip
@@ -293,14 +320,14 @@ if [ "$command" == "clip" ]; then
   $XCLIP -selection clipboard < "$publicKey"
 
   # END clip command
-elif [ "$command" == "copy" ]; then
+elif [ $command == 'copy' ]; then
   # BEGIN copy command
 
   # Display error and usage if incorrect parameters given
   if [ -z "$2" ]; then
-    printError "ssh-key" "Missing username@remote_server parameter"
+    printError 'ssh-key' 'Missing username@remote_server parameter'
     echo
-    printUsage "ssh-key copy username@remote_server"
+    printUsage 'ssh-key copy username@remote_server'
 
     exit 1
   fi
@@ -317,31 +344,31 @@ elif [ "$command" == "copy" ]; then
   $SSH_COPY_ID -i "$publicKey" -p $sshPort $userHost
 
   # END copy command
-elif [ "$command" == "fingerprint" ]; then
+elif [ $command == 'fingerprint' ]; then
   # BEGIN fingerprint command
 
   # Generate the publicKeyList
   publicKeyList=()
   while IFS=  read -r -d $'\0'; do
     publicKeyList+=("$REPLY")
-  done < <(find "$sshDir" -type f -name '*.pub' -print0)
+  done < <($EXEC_FIND "$sshDir" -type f -name '*.pub' -print0)
 
   for publicKey in "${publicKeyList[@]}"; do
     $SSH_KEYGEN -l -v -f "$publicKey"
   done
 
   # END fingerprint command
-elif [ "$command" == "gen" ] || [ "$command" == "generate" ]; then
+elif [ $command == 'gen' ] || [ $command == 'generate' ]; then
   # BEGIN gen/generate command
 
-  printBanner "Generating SSH Keys"
-  hostName=$(hostname)
+  printBanner 'Generating SSH Keys'
+  hostName=$($EXEC_HOSTNAME)
 
-  echo -e "$(bold yellow)NOTE: It is highly recommended to use a long random passphrase$(reset)"
-  echo
+  echo ${bold}${yellow}'NOTE: It is highly recommended to use a long random passphrase'
+  echo ${white}
 
   # Question 1
-  echo -n "What email address do you want to use for the SSH key? "
+  echo -n 'What email address do you want to use for the SSH key? '
   read emailAddress
   echo
 
@@ -350,36 +377,36 @@ elif [ "$command" == "gen" ] || [ "$command" == "generate" ]; then
   fi
 
   # Question 2
-  sshFile="$username-$hostName-id_$keyType"
-  echo -n "What filename do you want to use for the SSH key ($sshFile)? "
+  sshKeyName="$username-$hostName-id_$keyType"
+  echo -n "What filename do you want to use for the SSH key ($sshKeyName)? "
   read filename
   echo
 
   if [ ! -z "$filename" ]; then
-    sshFile="$filename"
+    sshKeyName="$filename"
   fi
 
   # Generate SSH key
-  $SSH_KEYGEN -t $keyType -C "$emailAddress-$(date -I)" -f "$sshDir/$sshFile"
+  $SSH_KEYGEN -t $keyType -C "$emailAddress-$($EXEC_DATE -I)" -f "$sshDir/$sshKeyName"
 
   # Change directory and file ownership to $username
-  chown -R $username:$username "$sshDir"
+  $EXEC_CHOWN -R $username:$username "$sshDir"
 
   # END gen/generate command
-elif [ "$command" == "list" ]; then
+elif [ $command == 'list' ]; then
   # BEGIN list command
 
-  printBanner "Listing SSH Public Keys"
+  printBanner 'Listing SSH Public Keys'
 
-  find "$sshDir" -maxdepth 1 -type f -name "*.pub"
+  $EXEC_FIND "$sshDir" -maxdepth 1 -type f -name "*.pub"
 
   echo
 
   # END list command
-elif [ "$command" == "pass" ] || [ "$command" == "passphrase" ]; then
+elif [ $command == 'pass' ] || [ $command == 'passphrase' ]; then
   # BEGIN pass/passphrase command
 
-  printBanner "Changing SSH Private Key Passphrase"
+  printBanner 'Changing SSH Private Key Passphrase'
 
   # Find the private key the user wants to change the passphrase
   findPrivateKey
@@ -391,4 +418,3 @@ elif [ "$command" == "pass" ] || [ "$command" == "passphrase" ]; then
 fi
 
 exit 0
-
