Revamped qemu-config utility for Ubuntu 18.04

diff --git a/Ubuntu/18.04/Utilities/usr/local/bin/qemu-config b/Ubuntu/18.04/Utilities/usr/local/bin/qemu-config
--- a/Ubuntu/18.04/Utilities/usr/local/bin/qemu-config
+++ b/Ubuntu/18.04/Utilities/usr/local/bin/qemu-config
@@ -50,24 +50,27 @@ ${FUNC_CONFIG?"[1;91mCannot load '/etc/devops/functions.conf': No such file[0m
 ################################## Functions ##################################
 
 # ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
-# Function:	showHelp
-# Description:	Displays help message to the user
+# Function:     showHelp
+# Description:  Displays help message to the user
 # -----------------------------------------------------------------------------
 function showHelp() {
-  # BEGIN showHelp function
+	# BEGIN showHelp function
 
-  printUsage "qemu-config image ${gold}[-d directory] ${yellow}IMG_FILE SIZE"
-  printUsage 'false' "qemu-config init ${gold}[-d directory]"
-  printUsage 'false' "qemu-config help ${gold}[OPTION]..."
+	if [ "$command" == 'image' ]; then
+		printUsage "qemu-config image ${gold}[-d directory] ${yellow}IMG_FILE SIZE"
+		echo ${romantic}
+		echo 'Creates a new QEMU image file IMG_FILE of SIZE'${reset}
+	elif [ "$command" == 'info' ]; then
+		printUsage "qemu-config info ${gold}[OPTION]..."
+		echo ${romantic}
+		echo 'Easily review help information for various QEMU components'${reset}
+	elif [ "$command" == 'init' ]; then
+		printUsage "qemu-config init ${gold}[-d directory]"
+		echo ${romantic}
+		echo 'Copies OVMF UEFI BIOS, keymap, and generates a random MAC Address and UUID'${reset}
+	fi
 
-  echo ${bold}
-  echo "Valid Commands:${romantic}"
-  echo -e '  image\t\t'		'Create a new QEMU image file of SIZE'
-  echo -e '  init\t\t'		'Copies OVMF UEFI BIOS, keymap, and generates a random MAC Address and UUID'
-  echo -e '  help\t\t'		'Easily review help for various QEMU components'
-  echo ${reset}
-
-  # END showHelp function
+	# END showHelp function
 }
 
 ################################## Variables ##################################
@@ -78,215 +81,270 @@ EXEC_QEMU_IMG=/usr/bin/qemu-img
 EXEC_MACADDR=/usr/local/bin/macaddr
 EXEC_UUID=/usr/local/bin/uuid
 
-validCommands=('image' 'init' 'help')
-
-# Usage message map
-declare -A usageMsgMap
-
-usageMsgMap['image']="qemu-config image ${gold}[-d directory] ${yellow}IMG_FILE SIZE"
-usageMsgMap['bios']="qemu-config bios ${gold}[-d directory]"
-
 # Options
 command="$1"
 QEMU_DIR='.'
 
+## Variables
+showCommandHelp=false
+validCommands=('image' 'info' 'init')
+
+declare -A usageMsgMap
+
+usageMsgMap['image']="qemu-config image ${gold}[-d directory] ${yellow}IMG_FILE SIZE"
+usageMsgMap['init']="qemu-config init ${gold}[-d directory]"
+
 #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ OPTION Parsing ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
-# Display usage if no parameters given
-if [ -z $command ]; then
-  showHelp
+if [ "$command" == 'help' ]; then
+	showCommandHelp=true
+	command="$2"
+	shift
+fi
 
-  exit 1
+# Display usage if no parameters given
+if [ -z "$command" ]; then
+	printUsage "qemu-config ${gold}[help]${yellow} { image | info | init }"
+	exit 1
 fi
 
 # Display error if invalid command
 if [ $(containsElement "$command" "${validCommands[@]}") != '0' ]; then
-  printError 'qemu-config' "Invalid command: $command"
-  echo
+	printError 'qemu-config' "Invalid command: '$command'"
+	echo
+	printUsage "qemu-config ${gold}[help]${yellow} { image | info | init }"
 
-  showHelp
+	exit 1
+fi
 
-  exit 1
+if [ "$showCommandHelp" == 'true' ]; then
+	showHelp
+	exit 0
 fi
 
 # Process command-line options, if present
 while [[ "$2" =~ ^- ]]; do
 
-  if [ "$2" = '-d' ]; then
+	if [ "$2" = '-d' ]; then
 
-    errorMessage=$(isValidDirectory 'qemu-config' "$3")
+		errorMessage=$(isValidDirectory 'qemu-config' "$3")
 
-    # Display error if directory parameter is missing or invalid
-    if [ "$errorMessage" != '0' ]; then
-      echo "$errorMessage"
-      echo
-      printUsage "${usageMsgMap[$command]}"
+		# Display error if directory parameter is missing or invalid
+		if [ "$errorMessage" != '0' ]; then
+			echo "$errorMessage"
+			echo
+			printUsage "${usageMsgMap[$command]}"
 
-      exit 1
-    fi
+			exit 1
+		fi
 
-    # Use virtual machine image directory provided by user
-    QEMU_DIR="$3"
+		# Use virtual machine image directory provided by user
+		QEMU_DIR="$3"
+		shift 2
 
-    shift 2
+	else
+		# Display usage and error if option parameter is not valid
+		printError 'qemu-config' "Invalid option: $2"
+		echo
+		printUsage "${usageMsgMap[$command]}"
 
-  else
-    # Display usage and error if option parameter is not valid
-    printError 'qemu-config' "Invalid option: $2"
-    echo
-    printUsage "${usageMsgMap[$command]}"
-
-    exit 1
-  fi
+		exit 1
+	fi
 
 done
 
 if [ $command == 'image' ]; then
 
-  IMG_FILE="$2"
-  IMG_SIZE="$3"
+	IMG_FILE="$2"
+	IMG_SIZE="$3"
 
-  # Display error if no file parameter given
-  if [ -z "$IMG_FILE" ]; then
-    printError 'qemu-config' 'Missing file parameter'
-    echo
-    printUsage "qemu-config image ${gold}[-d directory] ${yellow}IMG_FILE SIZE"
+	# Display error if no file parameter given
+	if [ -z "$IMG_FILE" ]; then
+		printError 'qemu-config' 'Missing file parameter'
+		echo
+		printUsage "qemu-config image ${gold}[-d directory] ${yellow}IMG_FILE SIZE"
 
-    exit 1
-  fi
+		exit 1
+	fi
 
-  # Append .img to filename, if not already present
-  if [[ "$IMG_FILE" != *.img ]]; then
-    IMG_FILE=$IMG_FILE'.img'
-  fi
+	# Append .img to filename, if not already present
+	if [[ "$IMG_FILE" != *.img ]]; then
+		IMG_FILE=$IMG_FILE'.img'
+	fi
 
-  # Display error if image file already exists
-  if [ -f "$QEMU_DIR/$IMG_FILE" ]; then
-    printError 'qemu-config' "Invalid image file '$IMG_FILE': File already exists"
-    echo
-    printUsage "qemu-config image ${gold}[-d directory] ${yellow}IMG_FILE SIZE"
+	# Display error if image file already exists
+	if [ -f "$QEMU_DIR/$IMG_FILE" ]; then
+		printError 'qemu-config' "Invalid image file '$IMG_FILE': File already exists"
+		echo
+		printUsage "qemu-config image ${gold}[-d directory] ${yellow}IMG_FILE SIZE"
 
-    exit 1
-  fi
+		exit 1
+	fi
 
-  # Display error if no image size parameter given
-  if [ -z "$IMG_SIZE" ]; then
-    printError 'qemu-config' 'Missing QEMU image file size parameter'
-    echo
-    printUsage "qemu-config image ${gold}[-d directory] ${yellow}$IMG_FILE SIZE"
+	# Display error if no image size parameter given
+	if [ -z "$IMG_SIZE" ]; then
+		printError 'qemu-config' 'Missing QEMU image file size parameter'
+		echo
+		printUsage "qemu-config image ${gold}[-d directory] ${yellow}$IMG_FILE SIZE"
 
-    exit 1
-  fi
+		exit 1
+	fi
 
-  # Display error if image size suffix is invalid
-  if [[ ! "$IMG_SIZE" =~ (k|K|M|G|T)$ ]]; then
-    printError 'qemu-config' "Invalid QEMU image size suffix: $IMG_SIZE"
-    echo
-    printUsage "qemu-config image ${gold}[-d directory] ${yellow}$IMG_FILE SIZE"
-    echo ${bold}
-    echo "Valid Size Suffixes:${romantic}"
-    echo -e '  k or K\t'	'kilobyte, 1024'
-    echo -e '  M\t\t'		'megabyte, 1024k'
-    echo -e '  G\t\t'		'gigabyte, 1024M'
-    echo -e '  T\t\t'		'terabyte, 1024G'
-    echo ${reset}
+	# Display error if image size suffix is invalid
+	if [[ ! "$IMG_SIZE" =~ (k|K|M|G|T)$ ]]; then
+		printError 'qemu-config' "Invalid QEMU image size suffix: $IMG_SIZE"
+		echo
+		printUsage "qemu-config image ${gold}[-d directory] ${yellow}$IMG_FILE SIZE"
+		echo ${bold}
+		echo "Valid Size Suffixes:${romantic}"
+		echo -e '  k or K\t'	'kilobyte, 1024'
+		echo -e '  M\t\t'		'megabyte, 1024k'
+		echo -e '  G\t\t'		'gigabyte, 1024M'
+		echo -e '  T\t\t'		'terabyte, 1024G'
+		echo ${reset}
 
-    exit 1
-  fi
+		exit 1
+	fi
 
-  # Display error if image size is invalid
-  if [[ ! "$IMG_SIZE" =~ ^[0-9]+(k|K|M|G|T)$ ]]; then
-    printError 'qemu-config' "Invalid image size: $IMG_SIZE"
-    echo
-    printUsage "qemu-config image ${gold}[-d directory] ${yellow}$IMG_FILE SIZE"
+	# Display error if image size is invalid
+	if [[ ! "$IMG_SIZE" =~ ^[0-9]+(k|K|M|G|T)$ ]]; then
+		printError 'qemu-config' "Invalid image size: $IMG_SIZE"
+		echo
+		printUsage "qemu-config image ${gold}[-d directory] ${yellow}$IMG_FILE SIZE"
 
-    exit 1
-  fi
+		exit 1
+	fi
 
-  # END image command
-elif [ $command == 'help' ]; then
-
-  if [ -z "$2" ]; then
-    helpArgs='-h'
-  elif [ "$2" == 'audio' ]; then
-    helpArgs='-audio-help'
-  elif [ "$2" == 'cpu' ]; then
-    helpArgs='-cpu help'
-  elif [ "$2" == 'device' ]; then
-    helpArgs='-device '
-
-    if [ -z "$3" ]; then
-      helpArgs=$helpArgs'help'
-    else
-      helpArgs=$helpArgs"$3,help"
-    fi
-  elif [ "$2" == 'machine' ]; then
-    helpArgs='-machine help'
-  elif [ "$2" == 'nic' ]; then
-    helpArgs='-net nic,model=help'
-  elif [ "$2" == 'soundhw' ]; then
-    helpArgs='-soundhw help'
-  elif [ "$2" == 'tpmdev' ]; then
-    helpArgs='-tpmdev help'
-  elif [ "$2" == 'watchdog' ]; then
-    helpArgs='-watchdog help'
-  else
-    printError 'qemu-config' "Invalid help topic: $2"
-
-    echo ${bold}
-    echo "Valid Options:${romantic}"
-    echo -e '  help\t\t'	'View help on the qemu-system parameters and settings'
-    echo -e '    audio\t\t'		'List the audio subsystem drivers and tunable parameters'
-    echo -e '    cpu\t\t\t'		'List CPU models and view additional feature selections'
-    echo -e '    device [driver]\t'	'Get help on possible device drivers and properties'
-    echo -e '    machine\t\t'		'View available QEMU machines'
-    echo -e '    nic\t\t\t'		'List of available networking devices for your target'
-    echo -e '    soundhw\t\t'		'List all available sound hardware'
-    echo -e '    tpmdev\t\t'		'View all available TPM backend types'
-    echo -e '    watchdog\t\t'		'List available hardware watchdog models'
-    echo ${reset}
-
-    exit 1
-  fi
-
-  # END help command
+	# END image command
 fi
 
 ################################### Actions ###################################
 
 if [ $command == 'image' ]; then
 
-  printInfo "Creating QEMU image $QEMU_DIR/$IMG_FILE"
+	printInfo "Creating QEMU image $QEMU_DIR/$IMG_FILE"
 
-  $EXEC_QEMU_IMG create -f raw "$QEMU_DIR/$IMG_FILE" ${IMG_SIZE}
-  $EXEC_CHOWN $USER:kvm "$QEMU_DIR"
-  $EXEC_CHOWN $USER:kvm "$QEMU_DIR/$IMG_FILE"
+	$EXEC_QEMU_IMG create -f raw "$QEMU_DIR/$IMG_FILE" ${IMG_SIZE}
+	$EXEC_CHOWN $USER:kvm "$QEMU_DIR"
+	$EXEC_CHOWN $USER:kvm "$QEMU_DIR/$IMG_FILE"
 
 elif [ $command == 'init' ]; then
 
-  printBanner "Initializing QEMU Virtual Machine"
+	printBanner "Initializing QEMU Virtual Machine"
 
-  if [ ! -f "$QEMU_DIR"/bios.bin ]; then
-    printInfo "Copying OVMF UEFI BIOS to $QEMU_DIR"
+	if [ ! -f "$QEMU_DIR"/bios.bin ]; then
+		printInfo "Copying OVMF UEFI BIOS to $QEMU_DIR"
+		$EXEC_CP /usr/share/qemu/OVMF.fd "$QEMU_DIR"/bios.bin
+	fi
 
-    $EXEC_CP /usr/share/qemu/OVMF.fd "$QEMU_DIR"/bios.bin
-  fi
+	if [ ! -f "$QEMU_DIR"/en-us ]; then
+		printInfo "Copying en-us keymap to $QEMU_DIR"
+		$EXEC_CP /usr/share/qemu/keymaps/en-us "$QEMU_DIR"/
+	fi
 
-  if [ ! -f "$QEMU_DIR"/en-us ]; then
-    printInfo "Copying en-us keymap to $QEMU_DIR"
+	# qemu MAC address must begin with 52:54
+	echo
+	echo -e "MAC Address:\t $( $EXEC_MACADDR '52:54' )"
+	echo -e "UUID:\t\t $( $EXEC_UUID )"
+	echo
 
-    $EXEC_CP /usr/share/qemu/keymaps/en-us "$QEMU_DIR"/
-  fi
+elif [ $command == 'info' ]; then
 
-  # qemu MAC address must begin with 52:54
-  echo
-  echo -e "MAC Address:\t $( $EXEC_MACADDR '52:54' )"
-  echo -e "UUID:\t\t $( $EXEC_UUID )"
-  echo
+	sortOutput=false
 
-elif [ $command == 'help' ]; then
+	if [ -z "$2" ]; then
 
-  $EXEC_QEMU $helpArgs 2>&1
+		helpArgs='--h'
+
+	elif [ "$2" == 'audio' ]; then
+
+		helpArgs='--audio-help'
+
+	elif [ "$2" == 'chardev' ]; then
+
+		mapfile chardevList < <($EXEC_QEMU --chardev help 2>&1)
+		unset chardevList[0]
+		sortedList=( $($EXEC_SORT <<<"${chardevList[@]}") )
+
+		echo ${bold}${white}'Available chardev backend types:'${reset}
+		printf "\n%s" "${sortedList[@]}"
+		printf "\n\n"
+		exit 0
+
+	elif [ "$2" == 'cpu' ]; then
+
+		helpArgs='--cpu help'
+
+	elif [ "$2" == 'device' ]; then
+
+		if [ -z "$3" ]; then
+			helpArgs='--device help'
+		else
+			helpArgs="--device $3,help"
+			sortOutput=true
+		fi
+
+	elif [ "$2" == 'machine' ]; then
+
+		if [ -z "$3" ]; then
+			helpArgs='--machine help'
+		else
+			helpArgs="--machine $3,help"
+			sortOutput=true
+		fi
+
+	elif [ "$2" == 'nic' ]; then
+
+		mapfile nicModelList < <($EXEC_QEMU --net nic,model=help 2>&1 | $EXEC_GREP -Eo '[a-z0-9_]+(,[a-z0-9_]+)+$' | $EXEC_TR "','" "'\n'")
+		sortedList=( $($EXEC_SORT <<<"${nicModelList[@]}") )
+
+		echo ${bold}${white}'Supported NIC models:'${reset}
+		printf "\n%s" "${sortedList[@]}"
+		printf "\n\n"
+		exit 0
+
+	elif [ "$2" == 'path' ]; then
+
+		helpArgs='--L help'
+		sortOutput=true
+
+	elif [ "$2" == 'soundhw' ]; then
+
+		helpArgs='--soundhw help'
+
+	elif [ "$2" == 'tpmdev' ]; then
+
+		helpArgs='--tpmdev help'
+
+	elif [ "$2" == 'watchdog' ]; then
+
+		helpArgs='--watchdog help'
+
+	else
+		printError 'qemu-config' "Invalid help topic: $2"
+		echo
+		echo ${bold}${white}'Valid Options:'${reset}
+		echo -e ${bold}${yellow}'  [none]\t\t'           ${romantic}'Display high-level QEMU help'
+		echo -e ${bold}${yellow}'  audio\t\t\t'          ${romantic}'List the audio subsystem drivers and tunable parameters'
+		echo -e ${bold}${yellow}'  chardev\t\t'          ${romantic}'View available character device backends'
+		echo -e ${bold}${yellow}'  cpu\t\t\t'            ${romantic}'List CPU models and view additional feature selections'
+		echo -e ${bold}${yellow}'  device [driver]\t'    ${romantic}'Get help on available device drivers and properties'
+		echo -e ${bold}${yellow}'  machine\t\t'          ${romantic}'View available QEMU machines'
+		echo -e ${bold}${yellow}'  nic\t\t\t'            ${romantic}'List of available networking devices'
+		echo -e ${bold}${yellow}'  path\t\t\t'           ${romantic}'List all the configured data directories'
+		echo -e ${bold}${yellow}'  soundhw\t\t'          ${romantic}'List all available sound hardware'
+		echo -e ${bold}${yellow}'  tpmdev\t\t'           ${romantic}'View all available TPM backend types'
+		echo -e ${bold}${yellow}'  watchdog\t\t'         ${romantic}'List available hardware watchdog models'
+		echo ${reset}
+
+		exit 1
+	fi
+
+	if [ "$sortOutput" == 'true' ]; then
+		$EXEC_QEMU $helpArgs 2>&1 | $EXEC_SORT
+	else
+		$EXEC_QEMU $helpArgs 2>&1
+	fi
 
 fi
 
